"""Versões oficiais do gerador e do contrato batch."""

GENERATOR_VERSION = "0.12.0"
BATCH_SCHEMA_VERSION = "1.7.3"
EVENT_SCHEMA_VERSION = "1.0.0"
TRANSACTION_LABEL_VERSION = "1.0.0"
QUALITY_SCENARIO_VERSION = "1.2.0"
