"""Versões oficiais do gerador e do contrato batch."""

GENERATOR_VERSION = "0.13.0"
BATCH_SCHEMA_VERSION = "1.8.0"
EVENT_SCHEMA_VERSION = "1.0.0"
TRANSACTION_LABEL_VERSION = "1.0.0"
QUALITY_SCENARIO_VERSION = "2.0.0"
